
// GET ALL PRODUCTS
GET http://localhost:4011/productlist/2


###

// GET ALL ON SALE PRODUCTS
GET http://localhost:4011/sale

###

// SORT BY BY ASCENDING OR DESCENDING
GET http://localhost:4011/productlist/price/desc

###


// FILTER BY FORMAT
GET http://localhost:4011/productlist/format/cassette


###

// ADD NEW PRODUCT
POST http://localhost:4011/productlist
Content-Type: application/json

{
    "Title": "BBAAABB",
    "Image": "some link",
    "Price": 22,
    "Description": "New Desc",
    "Format": "CD",
    "Availability": 1,
    "isOnline": 0,
    "OnSale": 0,
    "New": 0

}

###

// DELETE EXISTING PRODUCT
DELETE http://localhost:4011/productlist/14


###

// MAKE PRODUCT OFFLINE / ONLINE
PUT http://localhost:4011/productlist/3
Content-Type: application/json

{
    "isOnline": 1
}

###


// EDIT PRODUCT DETAILS
PUT http://localhost:4011/productlist/edit/25
Content-Type: application/json

{
    "Title": "A1LLLLAAA",
    "Price": 22,
    "Description": "New Desc",
    "Format": "CD",
    "Availability": 1,
    "isOnline": 1,
    "OnSale": 1
}

###

// GET ALL AVAILABLE PRODUCTS
GET http://localhost:4011/online
Content-Type: application/json


###
// LOGIN

POST http://localhost:4011/login
Content-Type: application/json

{
    "Email": "admin@gmail.com",
    "Password": "12345" 
}

// Have to set up the login POST command 

###

GET http://localhost:4011/new